//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace termProjectMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.tests = new HashSet<test>();
        }
    
        public int Id { get; set; }
        public string fname { get; set; }
        public string email { get; set; }
        public string contactno { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<test> tests { get; set; }
    }
}
