//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace termProjectMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities1 : DbContext
    {
        public Database1Entities1()
            : base("name=Database1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<company> companies { get; set; }
        public DbSet<degree> degrees { get; set; }
        public DbSet<institute> institutes { get; set; }
        public DbSet<question> questions { get; set; }
        public DbSet<score> scores { get; set; }
        public DbSet<technology> technologies { get; set; }
        public DbSet<test> tests { get; set; }
        public DbSet<user1> user1 { get; set; }
    }
}
