//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace termProjectMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class score
    {
        public int Id { get; set; }
        public Nullable<int> score1 { get; set; }
        public Nullable<int> testId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual test test { get; set; }
        public virtual user1 user1 { get; set; }
    }
}
