//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace termProjectMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public test()
        {
            this.questions = new HashSet<question>();
            this.scores = new HashSet<score>();
        }
    
        public int Id { get; set; }
        public Nullable<int> technologyId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<question> questions { get; set; }
        public virtual ICollection<score> scores { get; set; }
        public virtual technology technology { get; set; }
    }
}
